name: ci
on:
  push:
    branches:
      - docker
jobs:
  Dockerfile:
    env:
      file: Dockerfile
      pattern: started
      registry: index.docker.io
      repository: santander-anagrams
      sleep: 10
      tagname: ci
      user: barsanse
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build --file ${file} --no-cache --tag ${registry}/${user}/${repository}:${tagname} ${PWD}
      - name: run
        run: docker run --detach --entrypoint python --name ${repository} --volume "${PWD}/data:/data" ${registry}/${user}/${repository}:${tagname} anagrams.py
     
